### ISSUE TITLE
Rename up-client-zenoh-cpp to up-transport-zenoh-cpp to better reflect its purpose

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-transport-zenoh-cpp#52]
The "client" now lives in `up-cpp`. This repo will only contain a transport implementation. It should be renamed to reflect that and avoid confusion.

**Comment by PLeVasseur** [comment]
Hmm... what about other language implementations that define uP-L2 interfaces and allow for defining custom implementations for a particular transport? Would those repos still be `up-client`? Would they be `up-transport` unless and until they had a custom implementation of a uP-L2 API?

@stevenhartley might have more thoughts on this.

I also said a while back that e.g. the transport implementation of vsomeip should probably be called up-transport-vsomeip-foo, since _there will never be_ any uP-L2 stuff defined for it.

**Comment by gregmedd** [comment]
@PLeVasseur - Apologies for missing your question.

I think it is fine if other languages define their L2 APIs in a different way. In the C++ implementation, we are using up-cpp as the generic interface to uProtocol, with the various transport implementations only needing to provide their respective L1 capabilities. Given that, it makes sense for us to rename our repos.

And on the topic of renaming the repos, it looks like @stevenhartley already did that for us. Thanks!
